### PR TITLE
brainhubeu

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**

### CODE REVIEW

**Comment by ryhinchey** [comment]
Other presets are for open source packages.  I’m not sure it makes sense to open up presets for companies or where the line should be drawn in general for adding presets to this file.

It might make more sense to have a .envinfo file in your project that contains the configuration you want similar tools like eslint and Babel.

**Comment by piotr-s-brainhub** [comment]
@ryhinchey 

We have many Open Source packages https://www.npmjs.com/search?q=%40brainhubeu%2F and as we didn't get any response on this PR, we created our own package `@brainhubeu/envinfo`.

**Comment by ryhinchey** [comment]
@piotr-s-brainhub would having a file like .envinfo in each of your projects (similar to Babel/eslint) that had your config in it help you?

**Comment by piotr-s-brainhub** [comment]
@ryhinchey 

I haven't checked that but the `@brainhubeu/envinfo` package satisfies our needs so I close this PR.

**Pull request closed without merging**
