### PR TITLE
feat: add auto release

### PR DESCRIPTION
**Pull request by gengjiawen**
close https://github.com/tabrindle/envinfo/issues/109

Todo: you need to setup a token in https://github.com/tabrindle/envinfo/settings/secrets/actions with key as `NPM_TOKEN`

@tabrindle 

I have been using it in https://github.com/gengjiawen/monkey-rust, works like a charm.

### CODE REVIEW

**Comment by tabrindle** [comment]
@gengjiawen This is great work!

does this work with 2FA? I have it enabled on my npm account, and want to keep it.

**Comment by gengjiawen** [comment]
> does this work with 2FA? I have it enabled on my npm account, and want to keep it.

Not sure. I have not tested with 2FA yet.

**Comment by tabrindle** [comment]
Ok, token is up. Can you rebase so I can merge?

**Comment by gengjiawen** [comment]
done

**Pull request merged**
