### PR TITLE
fix: disable console formatter option when stdout is not terminal

### LINKED ISSUE #84: missing --yaml option
I know, I know, yaml is the default. You're losing your marbles Trevor. 

No!

When piping output to a file, or another binary, the output needs to be unformatted, not including any silly character escapes that we use in terminal for highlighting and bold. 

Right now, `npx envinfo | npx clipboard-cli` outputs

```
  [4mSystem:[0m
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.33 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
```

and since we can't possibly know where things are getting piped to, we need an option to specify the default format with no silly escaping

`npx envinfo --yaml >> envinfo.yaml` or `npx envinfo --yaml | npx clipboard-cli` should output without character escapes. 

Derp.

### PR DESCRIPTION
**Pull request by gowda**
closes #84

### CODE REVIEW

**Comment by tabrindle** [comment]
I was just thinking about doing this the other day because I just found out about isTTY :-|

Do you mind adding a test of some sort for this?

**Comment by gowda** [comment]
Sure. I will update with tests.

**Comment by gowda** [comment]
Updated with tests

**Comment by tabrindle** [comment]
This is fantastic, thanks!

**Pull request merged**
