### PR TITLE
Parse package path windows support

### PR DESCRIPTION
**Pull request by ryhinchey**
closes: https://github.com/tabrindle/envinfo/issues/160

I don't have a windows machine to test on but the tests should on appveyor

### CODE REVIEW

**Comment by thedavidprice** [comment]
I appreciate your help with this! Let me know when/if testing on Windows could be of help. If I'm not able to do it, I could easily ask the RedwoodJS community.

**Comment by thedavidprice** [comment]
Anything we can help test here? Thanks again!

**Comment by ryhinchey** [comment]
@thedavidprice im confident in this working given the test passed on appveyor.  That said, if you want to check out my branch and test locally on your windows machine, that’d be awesome!

**Comment by thedavidprice** [comment]
Tested locally and 🚀

Ship it! And huge thanks.

**Comment by ryhinchey** [comment]
> Tested locally and 🚀
> 
> Ship it! And huge thanks.

Awesome!  I'll merge this in now and will ping @tabrindle about getting a new release out the door :)

**Pull request merged**
