### PR TITLE
Show Google Chrome and Firefox versions on Linux

### PR DESCRIPTION
**Pull request by antonfisher**
Hi @tabrindle,
I noticed there are no versions for Google Chrome and Firefox on Linux, here is small PR to get them.

Before:
image

After:
image

### CODE REVIEW

**Comment by tabrindle** [comment]
While we are at it, it may be good to add an if statement on that else block until we get support for windows. 

Also obviously there's no safari for anything but macOS, but how might we get the other chrome/firefox versions?

**Comment by antonfisher** [comment]
I kept the previous solution as default one and placed it in the _else_ block: https://github.com/tabrindle/envinfo/pull/10/files#diff-b38f7254be1a9f817fd2e33c294481a1R338
Just for have the same behavior as before for all non-linux runs.
Do you think to add `if(linux)-elseif(win)-elseif(mac)-else` pattern to os-related methods?

As a common approach, I would separate `helpers.js` to `helpersBase.js` (all current methods) and `helpersLinux.js` what is just extends `helpersBase.js` and overwrite some methods for Linux only. The same is for Windows. Overwise there are going to be _if-elseif-else_ statements in each os-related method.
What do you think?

I didn't add canary and nightly just because I don't have them installed :)
I could add them too after I get them installed.

**Comment by tabrindle** [comment]
Well I will admit the way I did it before was bad - it just fail on anything but Mac. 

Some of these helpers will indeed need 3 different implementations, but a fair number are common between all three. 

I'm honestly ok with if else chains or switches for now. The bigger problem I need to figure out is filtering out unrelated programs from the output per OS.

**Comment by antonfisher** [comment]
I get it. Yes, would be great to filter out unrelated programs.
I just checked Chrome website and was surprised that "Chrome Canary is currently not available on the Linux platform."!
I installed Firefox Nightly and added it to the PR. Firefox Developer Edition installs and replaces default Firefox (https://askubuntu.com/questions/548003/how-do-i-install-the-firefox-developer-edition), so in this case, there is going to be a just updated version for "Firefox: XXX" output what actually shows Firefox Developer Edition version.
I don't know the right solution, the user even can install these packages manually and there is no way to figure out the versions.

**Comment by tabrindle** [comment]
Great work - indeed Linux seems to be way more difficult than macOS for
this.

I'll get working on modifying the formatter to take out programs labeled
N/A.

**Pull request merged**
