### PR TITLE
preset(playwright): add new packages

### PR DESCRIPTION
**Pull request by rwoll**
Playwright now has some additional supporting packages published under the `@playwright/*` npm scope (e.g. https://www.npmjs.com/package/@playwright/test from the docs https://playwright.dev/docs/api/class-test).

### CODE REVIEW

**Comment by mxschmitt** [comment]
There was previously a bug with the curly brackets syntax, that why I reverted it a few months ago, see here: https://github.com/tabrindle/envinfo/pull/188

**Comment by rwoll** [comment]
> There was previously a bug with the curly brackets syntax, that why I reverted it a few months ago, see here: https://github.com/tabrindle/envinfo/pull/188

@mxschmitt I think the old code was missing a comma for the singleton glob. The proposed change works locally (and I was able to repro and fix the old glob, although the issue no longer applies):

```
$ mkdir foo
$ cd foo
$ npm init -y
…
$ npm i playwright
…
$ # Original, broken glob
$ npx envinfo --npmPackages '{playwright*}'
[no output]

$ # Add a trailing comma for singleton makes globbing work
$ npx envinfo --npmPackages '{playwright*,}'

  npmPackages:
    playwright: ^1.14.0 => 1.14.0 

$ npm i -D @playwright/test
…
$ npx envinfo --npmPackages '{playwright*,@playwright/*}'

  npmPackages:
    @playwright/test: ^1.14.0 => 1.14.0 
    playwright: ^1.14.0 => 1.14.0 
```

Do you observe the same behavior?

**Comment by rwoll** [comment]
Closing this due to staleness. Feel free to re-open!

**Pull request closed without merging**
