### PR TITLE
fix: wrong duplicates

### PR DESCRIPTION
**Pull request by MoonBall**
Suppose that  contents of current project is as below:
image
You can download it to test: [envinfo-wrong-duplicates.zip](https://github.com/tabrindle/envinfo/files/3063874/envinfo-wrong-duplicates.zip)

executing `npx envinfo --npmPackages b --duplicates` in the project, the output is:
```
  npmPackages:
    b: 1.0.0 => 1.0.0
```
I think the result is not expected, and the correct result should be:
```
  npmPackages:
    b: 1.0.0 => 1.0.0 (1.0.2)
```

**I don't know how to add a  test for this case. Please give me a hint if it is necessary.**

### CODE REVIEW

**Comment by tabrindle** [comment]
This is an excellent find! Yes we should definitely have a test for this. 

We can probably generate a node_modules tree like in your example to create a test for this.

**Comment by MoonBall** [comment]
> This is an excellent find! Yes we should definitely have a test for this.
> 
> We can probably generate a node_modules tree like in your example to create a test for this.

@tabrindle  I prefer to add the test code in `envinfo.test.js` file rather than a new file. But methods of `../src/helpers` has been mocked in `envinfo.test.js`. I'd like to amend it if you have a better way.

**Comment by tabrindle** [comment]
No, I actually think what you did is perfect. It makes sense for it to be separate IMO. 

Thanks so much for the contribution - going to pull this and do some testing - hope to merge soon.

**Comment by MoonBall** [comment]
thanks

**Comment by tabrindle** [comment]
Quick thing I noticed while testing on the envinfo repo itself ` node dist/cli.js --npmPackages --duplicates --json` returns duplicates on minimist (as it should) but shows duplicates of the duplicates!

```
"minimist": {
      "duplicates": [
        "0.0.8",
        "0.0.8",
        "0.0.10"
      ],
      "installed": "1.2.0",
      "wanted": "^1.2.0"
    },
```

Could you update the PR to prevent this?

**Comment by MoonBall** [comment]
> Quick thing I noticed while testing on the envinfo repo itself ` node dist/cli.js --npmPackages --duplicates --json` returns duplicates on minimist (as it should) but shows duplicates of the duplicates!
> 
> ```
> "minimist": {
>       "duplicates": [
>         "0.0.8",
>         "0.0.8",
>         "0.0.10"
>       ],
>       "installed": "1.2.0",
>       "wanted": "^1.2.0"
>     },
> ```
> Could you update the PR to prevent this?

I fixed it. ☺

**Comment by tabrindle** [comment]
Looks good! Thanks 😀

**Pull request merged**
