### PR TITLE
add clang support.

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix https://github.com/tabrindle/envinfo/issues/86.

```console
  System:
    OS: Linux 4.15 Ubuntu 19.04 (Disco Dingo)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 31.36 GB / 68.69 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Utilities:
    CMake: 3.10.2 - /usr/local/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
    Clang: 8.0.0-3 - /usr/bin/clang
```

### CODE REVIEW

**Comment by gengjiawen** [comment]
@tabrindle ping.

**Comment by tabrindle** [comment]
sorry - can you add a test for this?

**Comment by gengjiawen** [comment]
> sorry - can you add a test for this?

Added.

**Comment by tabrindle** [comment]
Beautiful, thanks!

**Pull request merged**
